### PR TITLE
Add linters 

### PR DESCRIPTION
**Pull request by SelmaNdapanda**
In this pull request I implemented the following:

- Set up linters
- Added header and style
- modified README file
- Added a test.MD file to gitignore file

### CODE REVIEW

**Review by cynthiainga — CHANGES_REQUESTED** [review]
Hi @SelmaNdapanda, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- [ ] No linters errors ✔️ 
- [ ] Used the correct Github flow ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit messages ✔️ 

## Required Changes ♻️

- [ ] As I can't select the part that I would like to suggest to you some changes I will leave my comment in my summary 😊 😊.
- [x] Please kindly add the part of `Setup` in your README file that explains how to set up your app or website locally, and how to clone your repository locally,...🙃 🙃, you can refer to this [template](https://github.com/microverseinc/readme-template/blob/master/README.md)
- [x] Also delete the `s` to the word `Author` because you are the only one in this project, if you are many Authors in the project so then you can put `s` to ` Authors` 😁 😁


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SelmaNdapanda** [comment]
Hi @cynthiainga, I made the requested changes.

**Comment by cynthiainga** [comment]
Hi @SelmaNdapanda, that's nice but you can't request the review here you need to go to your dashboard and then ask for the second review 🙃 make sure to submit this pull request don't open another pull request 😁

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @SelmaNdapanda ,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️

_Check the comments below._

- As requested by the previous please kindly do the following below:
> * [x]  Please kindly add the part of `Setup` in your README file that explains how to set up your app or website locally, and how to clone your repository locally,...upside_down_face upside_down_face, you can refer to this [template](https://github.com/microverseinc/readme-template/blob/master/README.md)
> * [x]  Also delete the `s` to the word `Author` because you are the only one in this project, if you are many Authors in the project so then you can put `s` to ` Authors` grin grin
> 





## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zieeco — APPROVED** [review]
# status: APPROVED :green_circle: :100: 

Hi, @SelmaNdapanda, 


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
